### ISSUE TITLE
Problem with arrays of enums implementing an interface.

### ISSUE THREAD

**Issue by NemesisMate** [EsotericSoftware/yamlbeans#52]
I'm having troubles with the serialization of enums. Given an array containing elements from an interface, when it is serialized, the enums aren't tagged as such, and so, they can't be deserialized.
For example, having **enumArray** an array of an interface, YamlBeans serializes:

```
!test.YamlEnumTest$TestObject
enumArray: 
- V1
- V2
```

when it should be:

```
!test.YamlEnumTest$TestObject
enumArray: 
- !test.YamlEnumTest$CustomEnum V1
- !test.YamlEnumTest$CustomEnum V2
```

This could be fixed if an array could be tagged to use a default enum (just as it can be done with a collection) but it wouldn't work anyway if the array is filled with mixed values from different classes/enums implementing the interface, ie: where the serialization would be like:

```
!test.YamlEnumTest$TestObject
enumArray: 
- !test.YamlEnumTest$NonEnum
    v1: v1
    v2: v2
- !test.YamlEnumTest$CustomEnum V2
- !test.YamlEnumTest$CustomEnum2 VAL1
```

Well, all this is tested under the next code:

https://gist.github.com/NemesisMate/7152b60560161ff2154fad9d7827f2d0
