### ISSUE TITLE
underscore in package name cause YamlTokenizerError

### ISSUE THREAD

**Issue by jegesh** [EsotericSoftware/yamlbeans#68]
I spent close to an hour debugging this issue, it would be nice if it were documented (or, alternatively, not happen...).

Here's how to reproduce it:

yaml like this:

```
mainobject:
  customobjectlist:
    - !com.mydomain.my_package.MyObject
       prop1: hello
       prop2: world
```

When I took the underscore out of the package name, it worked as expected
